[package]
org = "choreo"
name = "ratelimit.token_based_ratelimit"
version = "1.0.0"
export = ["ratelimit.token_based_ratelimit"]
distribution = "2201.5.5"
keywords=["choreo-apim-mediation-policy", "choreo-apim-egress-ai", "choreo-apim-mediation-request-flow"]

[build-options]
observabilityIncluded = true
