[package]
org = "choreo"
name = "guardrail.sentence_count_guardrail"
version = "1.0.0"
export = ["guardrail.sentence_count_guardrail"]
distribution = "2201.5.5"
keywords = ["choreo-apim-mediation-policy","choreo-apim-mediation-request-flow","choreo-apim-mediation-response-flow","choreo-apim-egress-ai"]

[build-options]
observabilityIncluded = true
