[package]
org = "choreo"
name = "guardrail.azure_content_safety_content_moderation"
version = "1.0.0"
export = ["guardrail.azure_content_safety_content_moderation"]
distribution = "2201.5.5"
keywords = ["choreo-apim-mediation-policy","choreo-apim-mediation-request-flow","choreo-apim-mediation-response-flow","choreo-apim-egress-ai"]

[build-options]
observabilityIncluded = true
