name: Publish RC to Dev Central

on:
  workflow_dispatch:
    inputs:
      released-asset:
        description: The URL of the bala file to be pushed
        required: true
    
jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Ballerina
        run: |
          BAL_VERSION=2201.5.5
          BAL_INSTALLER=ballerina-$BAL_VERSION-swan-lake-linux-x64.deb
          wget https://dist.ballerina.io/downloads/$BAL_VERSION/$BAL_INSTALLER
          sudo dpkg -i $BAL_INSTALLER
      - name: Publish bala to dev Central
        env:
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BAL_DEV_CENTRAL_TOKEN }}
          BALLERINA_DEV_CENTRAL: true
        run: |
          BALA_URL=${{ github.event.inputs.released-asset }}
          wget $BALA_URL
          bal push $(basename $BALA_URL)
